language: node_js
services:
  - docker
sudo: required
node_js:
  - "8"
before_script:
  - docker pull lambci/lambda:build-nodejs8.10
script:
  - docker run -v $(pwd):/lambda -it lambci/lambda:build-nodejs8.10 /lambda/docker-test.sh
