import * as t from 'io-ts';
export declare const HexStringRT: t.RefinementType<t.StringType, string, string, t.mixed>;
export declare type HexString = t.TypeOf<typeof HexStringRT>;
export declare const Bytes32RT: t.RefinementType<t.RefinementType<t.StringType, string, string, t.mixed>, string, string, t.mixed>;
export declare type Bytes32 = t.TypeOf<typeof Bytes32RT>;
export declare const Bytes64RT: t.RefinementType<t.RefinementType<t.StringType, string, string, t.mixed>, string, string, t.mixed>;
export declare type Bytes64 = t.TypeOf<typeof Bytes64RT>;
export declare const TimestampRT: t.RefinementType<t.RefinementType<t.NumberType, number, number, t.mixed>, number, number, t.mixed>;
export declare type Timestamp = t.TypeOf<typeof TimestampRT>;
export declare const validNetworkNames: string[];
export declare const NetworkNameRT: t.RefinementType<t.StringType, string, string, t.mixed>;
export declare type NetworkName = t.TypeOf<typeof NetworkNameRT>;
export declare const EthAddressRT: t.RefinementType<t.StringType, string, string, t.mixed>;
export declare type EthAddress = t.TypeOf<typeof EthAddressRT>;
export declare const StellarAddressRT: t.RefinementType<t.StringType, string, string, t.mixed>;
export declare type StellarAddress = t.TypeOf<typeof StellarAddressRT>;
